### ISSUE TITLE
Fix resources/iso_parameterDirectionCode.yml naming

### ISSUE THREAD

**Issue by jwaspin** [adiwg/mdCodes#102]
The resources/iso_parameterDirectionCode.yml codelistName needs to match the filename

**Comment by hmaier-fws** [comment]
@jwaspin this isn't how most of the codelists are named. There's also an open issue to update the contribution guidelines, indicating that "Code" suffix should be removed (#44).

Unless there is some other reason to make the change, we should just leave the existing name as "iso_parameterDirection". (or to be consistent, include "Code" on all of the ISO codelist filenames)

**Comment by jwaspin** [comment]
@hmaier-fws I'll update the file to remove "Code" as a suffix. Wasn't sure which way to go on this.

**Comment by jwaspin** [comment]
Closed by #99
