### ISSUE TITLE
DCPList

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdCodes#11]
Suggest we change the codelist description to: "distributed computing platforms on which the operation has been implemented" or something like that. The current definition is unhelpful.

Shouldn't  _WwbService_ be _W**e**bService**s**_?

**Comment by stansmith907** [comment]
I agree the ISO definition is unhelpful.  I see  you took the definition from the SV_OperationMetadata's element distributedComputingPlatform.  I agree that this definition reads better.  I was also thinking perhaps they could be considered protocols and we could use the list for the protocol description with onlineResource.  

Yes, WebServices was misspelled.

**Comment by stansmith907** [comment]
I have made the changes to the YAML.  I will let you closes after you publish.
