### ISSUE TITLE
Add "deprecated" property to codelist items?

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdCodes#16]
This will allow filtering of deprecated codelist entries.

**Comment by stansmith907** [comment]
I added a 'deprecated: true' element to deprecated codelist elements, but I did not filter them out in any of the get routines yet, all codes are passed through.  We should discuss how we wish to handle the default query, (pass deprecated or filter deprecated).

**Comment by jlblcc** [comment]
I'm thinking we filter them by default and add a boolean "deprecated"  param to the API that will include them if true.

**Comment by jlblcc** [comment]
I don't think we need to have a method in mdCodes for that.

The API part is an issue that should be handled on the mdTranslator-rails repo.
