### ISSUE TITLE
Clarify associationType codes and definitions

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdCodes#17]
Correlating the ISO and sbJSON association types get murky when reading the provided definitions.  In particular not to let the code name influence the direction of the reference.  From reading the documentation I assume the direction to be 'how the associated resource relates to the main resource'.  So, 'the associated resource IS A __________ of the main resource.'  

### crossReference
* ISO: reference from one resource (dataset or project) to another
* Restated: the associated resource is reference to another dataset or project
Note: non-specific, non-directional

### largerWorkCitation
* ISO: reference to a master resource (dataset or project) of which this one is a part
* Restated: the associated resource is a citation of master resource to the main resource

### partOfSeamlessDatabase
* ISO: part of the same structured set of data held in a computer
* Restated: the associated resource is a part of the same structured set of data as the main resource

### source
* ISO: mapping and charting information from which the dataset content originates
* Restated: the associated resource is mapping and charting information from which the main resource content originates

### steroMate
* ISO: part of a set of imagery that when used together, provides three-dimensional images
* Restated: the associated resource is part of a set of imagery that when used together provide three-dimensional images
Note: no specific relationship to the main resource.

### isComposedOf
* ISO: reference to resources (datasets or projects) that are parts of this resource
* Restated: the associated resource is a dataset or project that is part of the main resource

### collectiveTitle
* ISO: common title for a collection of resources. NOTE Title identifies elements of a series collectively, combined with information about what volumes are available at the source cite.
* Restated: the associated resource is a common title for a collection of resources
Note: no specific relationship to the main resource, 

### series 
* ISO: associated through a common heritage such as produced to a common product specification
* Restated: the associated resource was produced via the same product specification as the main resource

### dependency
* ISO: associated through a dependency
* Restated: the associated resource is dependent on the main resource
Note: direction of dependency is uncertain 

### revisionOf
* ISO: resource is a revision of associated resource
* Restated: the main resource is revision of the associated resource
Note: reverses direction

### projectProduct
Note: deprecated by productOf.  However, productOf is this relationship but in the reverse direction.  
- [x] Recommendation: Reinstate. Rename to 'product'.

### supplementalResource
* ADIwg: supplemental resource
* Restated: the associated resource is a supplemental resource to the main resource

### produced
* ADIwg: reference to a product or deliverable produced by the resource (e.g. project or program)
* Restated: the associated resource is product produced from the main resource
Note: Verb? 
- [x] Recommendation: Drop this one.  Repetitive and the verb is confusing.

### productOf
* ADIwg: reference to a project or program which produced the resource as a deliverable
* Restated: the associated resource is the project or program which produced the main resource
Note: The code and definition reverse the relationship direction from associated resource -> main resource to how the main resource relates to the associated resource.
- [x] Recommendation: Drop this one.  Same as 'largerWorkCitation' and the renamed 'parentProject'.

### mainProjectOf
* ADIwg: reference to a project which is a derivative of the resource
* Restated: the associated resource is sub-project of the main resource
Note: The code and definition reverse the relationship direction from associated resource -> main resource to how the main resource relates to the associated resource. 
- [x] Recommendation: Rename to 'subProject'

### subProjectOf
* ADIwg: reference to a project of which the resource is a derivative
* Restated: the associated resource is a parent project of the main resource
Note: The code and definition reverse the relationship direction from associated resource -> main resource to how the main resource relates to the associated resource.  Same as 'largerWorkCitation'.
- [x] Recommendation: Rename to 'parentProject'

- [x] Recommendation: Replace the mdCodes definitions with the restated definitions above.

**Comment by jlblcc** [comment]
I agree with the changes above.  Making these changes will require a bump in the major version, or we could deprecate, see #16.

**Comment by stansmith907** [comment]
added 'deprecated:' element to deprecated items.

**Comment by stansmith907** [comment]
Moved issue to mdTranslator #106
