### ISSUE TITLE
Add 'observer' and 'curator' to iso-role codelist

### ISSUE THREAD

**Issue by stansmith907** [adiwg/mdCodes#24]
I have added the role of 'observer' to the *iso_roleType* codelist.  This is to identify the role of taxonomic observer or person(s) making the species identification.  

I added the role of 'curator' to the *iso_roleType* codelist.  This is to identify the role of curator for specimens deposited in a repository to support taxonomic identification.  

I think these roles were not inserted by ISO TC because taxonomy is an extension to the standards and not part of the ISO base.  Let me know if there are objections or better terminology.

**Comment by jlblcc** [comment]
Can we close this?
