### ISSUE TITLE
Possible conflict with entityType

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdCodes#25]
We now have both iso_entityType and adiwg_entityType. Do we want to rename iso_entityType? Otherwise, the mdEditor code will need to be adjusted to account for the prefix. It would be nice to have unique names without the prefix.

**Comment by jlblcc** [comment]
Maybe iso_entityDataType?

**Comment by stansmith907** [comment]
Maybe iso_entityClass?

**Comment by jlblcc** [comment]
elementEntityType?  Kinda weird, but the definition is: "datatype of element or entity"
