### ISSUE TITLE
New Codelist - Evaluation Method Type Code

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdCodes#37]
Relative to ISO 19157-2013, add new codelist

- Codelist Name: evaluationMethodTypeCode
- Name: iso_evaluationMethodTypeCode
- Source Name:  DQ_EvaluationMethodTypeCode
- Description: type of method for evaluating an identified data
quality measure
---
Code: 001
Code Name: directInternal
Description: method of evaluating the quality of a data set based on inspection of items within the data set, where all data required is internal to the data set being evaluated

Code: 002
Code Name: directExternal
Description: method of evaluating the quality of a data set based on inspection of items within the data set, where reference data external to the data set being evaluated is required

Code: 003
Code Name: indirect
Description: method of evaluating the quality of a data set based on external knowledge

**Comment by dwalt** [comment]
Added additional codes for method type sub-classes.

**Comment by dwalt** [comment]
Changed name to reflect difference between a type of Evaluation vs a type of Method Evaluation. The later being a report type.

**Comment by jwaspin** [comment]
https://github.com/adiwg/mdCodes/blob/feature/data-quality/resources/iso_evaluationMethodTypeCode.yml
