### ISSUE TITLE
Update characterSet?

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdCodes#7]
Should we use codes from http://www.iana.org/assignments/character-sets/character-sets.xhtml per 19115-1?

**Comment by stansmith907** [comment]
Looks like there were 3 codelists in -1 that were outsourced; language, country, and character set.  On the plus side it would not be too hard to add the new character set codes.  On the minus side we already have the official -2 character set codes in mdCodes so these would replaced.  But again, we maintain our own CT_CodelistCatalogue so I don't think it matters which list we use in -2 so long as we provide a reference to the catalog.  So, OK.  

Add it to 1.1.0 mdCodes?
