### ISSUE TITLE
Fix iso_geometryTypeCode

### ISSUE THREAD

**Issue by jwaspin** [adiwg/mdCodes#72]
resources/iso_geometryTypeCode.yml

Code name should be `strip`, not `stripe`

https://standards.iso.org/iso/19115/resources/Codelists/gml/MI_GeometryTypeCode.xml

https://wiki.esipfed.org/ISO_19115-3_Codelists#MI_GeometryTypeCode

**Comment by jwaspin** [comment]
@dwalt @hmaier-fws Before I make this change, I just want to double check that I am correct in doing this.

**Comment by hmaier-fws** [comment]
I concur. According to the above and https://schemas.isotc211.org/schemas/Resources/codelists.xml, `strip` is correct.

**Comment by dwalt** [comment]
Verified with ISO 19115-2 2019, strip is the correct code.
