### ISSUE TITLE
Fix Data Quality Reports List

### ISSUE THREAD

**Issue by jwaspin** [adiwg/mdCodes#78]
This list need to be verified for accuracy before making any changes (update this note as needed)...

adiwg_dataQualityElement.yml
resources/adiwg_dataQualityElement.yml

AbsoluteExternalPositionalAccuracy -> AbsolutePositionalAccuracy
AccuracyOfATimeMeasurement -> no change
ConceptualConsistency -> no change
CompletenessCommission -> Commission
CompletenessOmission -> Omission
Confidence -> remove
CoverageResult -> remove
DomainConsistency -> no change
FormatConsistency -> no change
GriddedDataPositionalAccuracy -> no change
Homogeneity -> remove
NonQuantitativeAttributeCorrectness -> no change
QuantitativeAttributeAccuracy -> no change
NonQuantitativeAttributeAccuracy -> remove (duplicate of NonQuantitativeAttributeCorrectness)
RelativeInternalPositionalAccuracy -> RelativePositionalAccuracy
Representativity -> remove
TemporalConsistency -> no change
TemporalValidity -> no change
ThematicClassificationCorrectness -> no change
TopologicalConsistency -> no change
UsabilityElement -> remove
Completeness -> remove (top level group, should not be listed specifically)
LogicalConsistency -> remove (top level group, should not be listed specifically)
PositionalAccuracy -> remove (top level group, should not be listed specifically)
TemporalQuality -> remove (top level group, should not be listed specifically)

**Comment by jwaspin** [comment]
@dwalt I looked through the existing list and the new list you sent me and I'm not entirely confident about all these changes, so I thought I'd map out the changes that appear to be needed. Before doing this I wanted to make sure the new list will be accurate, especially regarding the specific spellings/wording of some of them. The very first in the list is a good example: does it need to be AbsoluteExternalPositionalAccuracy or AbsolutePositionalAccuracy? It also appears we have extras in this list that don't belong, at least based on the list you provided, so I wanted to double check that removing those is also needed.

**Comment by dwalt** [comment]
@jwaspin I double checked the list I sent with ISO 19157: 2023 and it is correct and as it is spelled in the document. However, I did not include Metaquality reports of Confidence, Representativity and Homogeneity as I don't think we are building these reports. It does appear the reports have been refactored in the 2023 edition. One concern is that after removing the grouping labels, there is no logical organization of like reports. Do we modify report names to sort and identify report groupings?

**Comment by jwaspin** [comment]
@dwalt I think it's easy enough to have a mapping in the translator that can look at the type and determine its group. The same could be said for the editor if we want it grouped in the UI.

**Comment by dwalt** [comment]
@jwaspin However, there is still an issue of presenting these reports in the drop down list of report types whether the groupings are apparent. Maybe we try it and see if confusing or not.
